updated jenkinsfile deploy

diff --git a/Jenkinsfile-deploy b/Jenkinsfile-deploy
--- a/Jenkinsfile-deploy
+++ b/Jenkinsfile-deploy
@@ -39,6 +39,7 @@ pipeline {
             when {
                 expression { return params.NODE_CHOICE == 'local' && params.DEPLOY_TYPE == 'kubernetes' }
             }
+            agent { label 'local' } 
             steps {
                 script {
                     // Copy the kubeconfig file to the workspace
@@ -52,6 +53,7 @@ pipeline {
             when {
                 expression { return params.NODE_CHOICE == 'local' && params.DEPLOY }
             }
+            agent { label 'local' } 
             steps {
                 script {
                     // Check if the Nginx configuration file exists
@@ -81,6 +83,7 @@ pipeline {
             when {
                 expression { params.DEPLOY}
             }
+            agent { label 'local' } 
             steps {
                 script {
                     echo "Retrieve image tag from ${BUILD_PROJECT_NAME}"
@@ -145,41 +148,43 @@ pipeline {
                     sh "~/.docker/cli-plugins/docker-compose pull"
                     sh "~/.docker/cli-plugins/docker-compose up -d"
 
-                    // Trigger the new job for Docker deployment on AWS and wait for completion
-                    try {
-                        echo "Triggering 'aws_docker_deploy_job_numerical' with parameters:"
+                    echo "AWS Docker deployment completed."
 
-                        def dockerDeployJob = build(
-                            job: 'aws_docker_deploy_job_numerical', // Ensure this is the exact job name
-                            parameters: [
-                                string(name: 'NGINX_CONF', value: NGINX_CONF),
-                                string(name: 'SERVER_NAME', value: SERVER_NAME),
-                                string(name: 'DOCKER_PORT', value: DOCKER_PORT),
-                                string(name: 'AWS_PUBLIC_IP', value: AWS_IP),
-                                string(name: 'PROJECT_NAME_WITH_DASH', value: PROJECT_NAME_WITH_DASH),
-                                string(name: 'ENV_PROJECT_NAME', value: ENV_PROJECT_NAME),
-                            ],
-                            propagate: false, // Capture the result without failing the main pipeline immediately
-                            wait: true
-                        )
+                }
+            }
+        }
+        stage('Scale Down Kubernetes and Remove Docker When AWS Nde location') {
+            when {
+                expression { params.NODE_LOCATION == 'aws' && params.DEPLOY }
+            }
+            agent { label 'local' }  // Run this stage on the local node
+            steps {
+                script {
+                    echo "Scaling down Kubernetes deployment if it exists..."
+                    sh """
+                        replicas=\$(kubectl get deployment ${PROJECT_NAME_WITH_DASH}-app -o=jsonpath='{.spec.replicas}') || true
+                        if [ "\$replicas" != "" ] && [ \$replicas -gt 0 ]; then
+                            kubectl scale deployment ${PROJECT_NAME_WITH_DASH}-app --replicas=0
+                            echo 'Kubernetes deployment scaled down successfully.'
+                        else
+                            echo 'No running Kubernetes deployment to scale down.'
+                        fi
+                    """
 
-                        // Log the result of the job
-                        echo "Triggered job 'aws_docker_deploy_job_numerical' completed with result: ${dockerDeployJob.result}"
-
-                        if (dockerDeployJob.result == 'SUCCESS') {
-                            echo "AWS Docker deployment job completed successfully."
-                        } else {
-                            echo "AWS Docker deployment job failed with status: ${dockerDeployJob.result}"
-                            currentBuild.result = 'FAILURE'
-                            error("Stopping main pipeline due to failure in AWS Docker deployment job.")
-                        }
-                    } catch (Exception e) {
-                        echo "An error occurred while trying to trigger 'aws_docker_deploy_job_numerical'."
-                        echo "Exception message: ${e.getMessage()}"
-                        e.printStackTrace()  // Prints the full stack trace for more insight
-                        currentBuild.result = 'FAILURE'
-                        error("Stopping main pipeline due to an error when calling AWS Docker deployment job.")
-                    }
+                    echo "Checking for running local Docker container for project ${ENV_PROJECT_NAME}..."
+                    sh """
+                        DOCKER_CONTAINER=\$(docker ps -q -f name=${ENV_PROJECT_NAME})
+                        if [ "\$DOCKER_CONTAINER" ]; then
+                            echo "Docker container ${ENV_PROJECT_NAME} is running. Stopping and removing it..."
+                            docker rm -f ${ENV_PROJECT_NAME}
+                            if [ \$? -ne 0 ]; then
+                                echo "Failed to remove Docker container ${ENV_PROJECT_NAME}"
+                                exit 1
+                            fi
+                        else
+                            echo "Docker container ${ENV_PROJECT_NAME} is not running. Skipping removal."
+                        fi
+                    """
                 }
             }
         }
@@ -190,6 +195,7 @@ pipeline {
                     expression { params.NODE == 'local' }
                 }
             }
+            agent { label 'local' } 
             steps {
                 script {
                     if (params.DEPLOY_TYPE == 'docker') {
@@ -343,6 +349,7 @@ pipeline {
             when {
                 expression { params.DEPLOY }
             }
+            agent { label 'local' } 
             steps {
                 script {
                     echo "Sentry Release ..."
