updated jenkinsfile deploy

diff --git a/Jenkinsfile-deploy b/Jenkinsfile-deploy
--- a/Jenkinsfile-deploy
+++ b/Jenkinsfile-deploy
@@ -151,7 +151,17 @@ pipeline {
                     echo "AWS Docker deployment completed."
 
                     sleep 60
-                    
+                }
+            }
+        }
+        stage('Update Nginx & Scale Down Kubernetes and Remove Docker When AWS Nde location') {
+            when {
+                expression { params.NODE_LOCATION == 'aws' && params.DEPLOY }
+            }
+            agent { label 'local' }  // Run this stage on the local node
+            steps {
+                script {
+
                     // Check if the service is running on the AWS node by fetching HTTP status
                     try {
                         // Run curl with a timeout to prevent hanging
@@ -169,6 +179,33 @@ pipeline {
                                 sudo nginx -s reload
                             """
                             echo 'Nginx configuration updated and reloaded successfully.'
+
+                            echo "Scaling down Kubernetes deployment if it exists..."
+                            sh """
+                                replicas=\$(kubectl get deployment ${PROJECT_NAME_WITH_DASH}-app -o=jsonpath='{.spec.replicas}') || true
+                                if [ "\$replicas" != "" ] && [ \$replicas -gt 0 ]; then
+                                    kubectl scale deployment ${PROJECT_NAME_WITH_DASH}-app --replicas=0
+                                    echo 'Kubernetes deployment scaled down successfully.'
+                                else
+                                    echo 'No running Kubernetes deployment to scale down.'
+                                fi
+                            """
+
+                            echo "Checking for running local Docker container for project ${ENV_PROJECT_NAME}..."
+                            sh """
+                                DOCKER_CONTAINER=\$(docker ps -q -f name=${ENV_PROJECT_NAME})
+                                if [ "\$DOCKER_CONTAINER" ]; then
+                                    echo "Docker container ${ENV_PROJECT_NAME} is running. Stopping and removing it..."
+                                    docker rm -f ${ENV_PROJECT_NAME}
+                                    if [ \$? -ne 0 ]; then
+                                        echo "Failed to remove Docker container ${ENV_PROJECT_NAME}"
+                                        exit 1
+                                    fi
+                                else
+                                    echo "Docker container ${ENV_PROJECT_NAME} is not running. Skipping removal."
+                                fi
+                            """
+
                         } else {
                             echo "Service on AWS is not available. Nginx configuration not updated. HTTP Status: ${httpStatus}"
                             currentBuild.result = 'FAILURE'
@@ -180,42 +217,6 @@ pipeline {
                         currentBuild.result = 'FAILURE'
                         error("Stopping pipeline due to error in checking AWS service status or updating Nginx configuration.")
                     }
-
-                }
-            }
-        }
-        stage('Scale Down Kubernetes and Remove Docker When AWS Nde location') {
-            when {
-                expression { params.NODE_LOCATION == 'aws' && params.DEPLOY }
-            }
-            agent { label 'local' }  // Run this stage on the local node
-            steps {
-                script {
-                    echo "Scaling down Kubernetes deployment if it exists..."
-                    sh """
-                        replicas=\$(kubectl get deployment ${PROJECT_NAME_WITH_DASH}-app -o=jsonpath='{.spec.replicas}') || true
-                        if [ "\$replicas" != "" ] && [ \$replicas -gt 0 ]; then
-                            kubectl scale deployment ${PROJECT_NAME_WITH_DASH}-app --replicas=0
-                            echo 'Kubernetes deployment scaled down successfully.'
-                        else
-                            echo 'No running Kubernetes deployment to scale down.'
-                        fi
-                    """
-
-                    echo "Checking for running local Docker container for project ${ENV_PROJECT_NAME}..."
-                    sh """
-                        DOCKER_CONTAINER=\$(docker ps -q -f name=${ENV_PROJECT_NAME})
-                        if [ "\$DOCKER_CONTAINER" ]; then
-                            echo "Docker container ${ENV_PROJECT_NAME} is running. Stopping and removing it..."
-                            docker rm -f ${ENV_PROJECT_NAME}
-                            if [ \$? -ne 0 ]; then
-                                echo "Failed to remove Docker container ${ENV_PROJECT_NAME}"
-                                exit 1
-                            fi
-                        else
-                            echo "Docker container ${ENV_PROJECT_NAME} is not running. Skipping removal."
-                        fi
-                    """
                 }
             }
         }
